Added Keenetic OS detection support + running with /bin/sh (for run on EACH unix-like system with bash) (#43)
* Added Keenetic OS detection support

Added bash self-restart for support EACH unix-like environment via posix shebang /bin/sh
Added Keenetic OS detection support

* Fix: added Keenetic OS support to helps

* Fixed crash on distros with bash built as POSIX-strict

Thanks for Ivan Alone-san.

diff --git a/unifetch b/unifetch
--- a/unifetch
+++ b/unifetch
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # vim: noai:ts=4:sw=4:expandtab
 # shellcheck source=/dev/null
 # shellcheck disable=2009 disable=2153 disable=2154 disable=2243 disable=2244
@@ -28,6 +28,22 @@
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
+
+# Re-exec under Bash - supporting ANY Unix-like environment via a POSIX /bin/sh shebang
+if ! ( eval 'a=(1)' ) 2>/dev/null; then
+    if command -v bash >/dev/null 2>&1; then
+        exec bash "$0" "$@"
+    elif command -v osh >/dev/null 2>&1; then
+        exec osh "$0" "$@"
+    else
+        echo "Error: bash-compatible shell was not found!" >&2
+        exit 1
+    fi
+else
+    # Disable POSIX strict mode (e.g., to allow sourcing non-existent files when 
+    # /bin/sh is a symlink to the bash binary compiled in POSIX mode, as in Arch).
+    set +o posix 2>/dev/null || true
+fi
 
 version=1.3.3
 nf_version=7.4.3.3
@@ -816,8 +832,8 @@ image_source="auto"
 # Endless, Enso, EuroLinux, EvolutionOS, Exherbo, Exodia Predator OS, Fedora, Feren, Finnix, Floflis FreeBSD, FreeMiNT,
 # Frugalware, Funtoo, GalliumOS, Garuda, Gentoo, GhostBSD, glaucus, gNewSense, GNOME, GNU,
 # GoboLinux, GrapheneOS, Grombyang, Guix, Haiku, HarDClanZ, Hash, Huayra, Hybrid, HydroOS, Hyperbola,
-# iglunix, instantOS, IRIX, Itc, januslinux, Kaisen, Kali, Kamuriki, KaOS, KDE, Kibojoe, KLAE, Kogaion, Korora,
-# KrassOS, KSLinux, Kubuntu, LainOS, LangitKetujuh, LaxerOS, LEDE, LibreELEC, Linspire, Linux, Linux Lite,
+# iglunix, instantOS, IRIX, Itc, januslinux, Kaisen, Kali, Kamuriki, KaOS, KDE, Keenetic OS, Kibojoe, KLAE, Kogaion,
+# Korora, KrassOS, KSLinux, Kubuntu, LainOS, LangitKetujuh, LaxerOS, LEDE, LibreELEC, Linspire, Linux, Linux Lite,
 # Linux Mint, Linux Mint Old, Live Raizo, LMDE, Lubuntu, Lunar, mac, Mageia, MagpieOS, MainsailOS, Mandriva,
 # Manjaro, MassOS, MatuusOS, Maui, Mer, Minix, MIRACLE LINUX, Moevalent, MOS, MX, Namib, Neptune, NetBSD, Netrunner,
 # Nitrux, NixOS, NNLinux, NomadBSD, Nurunner, NuTyX, Obarun, OBRevenge, Open Source Media Center,
@@ -1189,6 +1205,18 @@ get_distro() {
                 distro="Synology DSM ${productversion}-${buildnumber} Update ${smallfixnumber}"
 
             else
+               if [ -f /bin/ndmc ]; then
+                    if [ -z "$__NDM_OUT_VER" ]; then
+                        __NDM_OUT_VER=$(/bin/ndmc -c "show version" 2>/dev/null )
+                    fi
+                    if [ ! -z "$__NDM_OUT_VER" ]; then
+                        n_ven=$( echo "$__NDM_OUT_VER" | awk -F': ' '/vendor/ {print $2}' )
+                        n_ver=$( echo "$__NDM_OUT_VER" | awk -F': ' '/title/ {print $2}' )
+                        distro="$n_ven OS $n_ver"
+                        break
+                    fi
+                fi
+
                 for release_file in /etc/*-release; do
                     distro+=$(< "$release_file")
                 done
@@ -1403,6 +1431,16 @@ get_model() {
 
             elif [[ -f /tmp/sysinfo/model ]]; then
                 model=$(< /tmp/sysinfo/model)
+
+            elif [ -f /bin/ndmc ]; then
+                if [ -z "$__NDM_OUT_VER" ]; then
+                    __NDM_OUT_VER=$(/bin/ndmc -c "show version" 2>/dev/null )
+                fi
+                if [ ! -z "$__NDM_OUT_VER" ]; then
+                    n_ven=$( echo "$__NDM_OUT_VER" | awk -F': ' '/vendor/ {print $2}' )
+                    n_mod=$( echo "$__NDM_OUT_VER" | awk -F': ' '/model/ {print $2}' )
+                    model="$n_ven $n_mod"
+                fi
             fi
         ;;
 
@@ -4878,6 +4916,8 @@ print_ascii() {
     ascii_data="${ascii_data//\$\{c4\}/$c4}"
     ascii_data="${ascii_data//\$\{c5\}/$c5}"
     ascii_data="${ascii_data//\$\{c6\}/$c6}"
+    ascii_data="${ascii_data//\$\{bw\}/$( printf '\e[47m' )}"
+    ascii_data="${ascii_data//\$\{rs\}/$( printf '\e[0m' )}"
 
     ((text_padding=ascii_len+gap))
     printf '%b\n' "$ascii_data${reset}"
@@ -5973,8 +6013,8 @@ ASCII:
                                 Endless, Enso, EuroLinux, EvolutionOS, Exherbo, Exodia Predator OS, Fedora, Feren, Finnix, Floflis, FreeBSD,
                                 FreeMiNT, Frugalware, Funtoo, GalliumOS, Garuda, Gentoo, GhostBSD, glaucus, gNewSense, GNOME, GNU,
                                 GoboLinux, GrapheneOS, Grombyang, Guix, Haiku, HarDClanZ, Hash, Huayra, Hybrid, HydroOS, Hyperbola,
-                                iglunix, instantOS, IRIX, Itc, januslinux, Kaisen, Kali, Kamuriki, KaOS, KDE, Kibojoe, KLAE, Kogaion, Korora,
-                                KrassOS, KSLinux, Kubuntu, LainOS, LangitKetujuh, LaxerOS, LEDE, LibreELEC, Linspire, Linux, Linux Lite,
+                                iglunix, instantOS, IRIX, Itc, januslinux, Kaisen, Kali, Kamuriki, KaOS, KDE, Keenetic OS, Kibojoe, KLAE, Kogaion,
+                                Korora, KrassOS, KSLinux, Kubuntu, LainOS, LangitKetujuh, LaxerOS, LEDE, LibreELEC, Linspire, Linux, Linux Lite,
                                 Linux Mint, Linux Mint Old, Live Raizo, LMDE, Lubuntu, Lunar, mac, Mageia, MagpieOS, MainsailOS, Mandriva,
                                 Manjaro, MassOS, MatuusOS, Maui, Mer, Minix, MIRACLE LINUX, Moevalent, MOS, MX, Namib, Neptune, NetBSD, Netrunner,
                                 Nitrux, NixOS, NNLinux, NomadBSD, Nurunner, NuTyX, Obarun, OBRevenge, Open Source Media Center,
@@ -11483,6 +11523,26 @@ ${c1}   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    ██   ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
    ██   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀██
    ██                       ██
+   ███████████████████████████
+EOF
+        ;;
+
+        "Keenetic OS"*)
+            set_colors 4 7 3
+            read -rd '' ascii_data <<'EOF'
+${c1}   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
+   ███████████████████████████
+   ███████████████████████████
+   ${bw}███    ██████████▀    ▄████${rs}${c1}
+   ${bw}███    ████████▀    ▄██████${rs}${c1}
+   ${bw}███    ██████▀    ▄████████${rs}${c1}
+   ${bw}███              ▀▀████████${rs}${c1}
+   ${bw}███                  ▀█████${rs}${c1}
+   ${bw}███    █████████▄▄▄    ████${rs}${c1}
+   ${bw}███    █████████████    ███${rs}${c1}
+   ${bw}███    █████████████    ███${rs}${c1}
+   ███████████████████████████
+   ███████████████████████████
    ███████████████████████████
 EOF
         ;;
